[package]
name = "arpack"
version = "0.1.0"
authors = ["Magnus Ulimoen <magnus@ulimoen.dev>"]
edition = "2018"

[dependencies]
arpack-sys = { path = "arpack-sys" }

[workspace]
members = ["arpack-sys"]

[dev-dependencies]
approx = "0.4.0"
